### ISSUE TITLE
Warning messages for css modules

### ISSUE THREAD

**Issue by magp** [FuriKuri/generator-d3-starter-kit#1]
Thanks for the d3 generator, it's much appreciated.

I don't think it's critical but I'm getting warning messages for css-select and css-what. Not sure if it's the actual package or one of its dependencies. 

```
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
```

I'm happy to provide further info if needed.

EDIT: Forgot message.

**Comment by FuriKuri** [comment]
I updated the yeoman-generator version.

**Comment by magp** [comment]
Thanks for the quick response and solution.
